# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDJxre_6WQjxetIbqaM_-BLlAeU5657g
"""

print(5/8)
print(7+10)
print("Hello Python")
print(4**2)
print(18%7)
print(1000*1.1**15)
savings = 20000
factor = 1.35
result = savings * factor ** 15
print (result)
desc = "uyuy"
profitable = True


print(type(savings))
print(type(factor))
print(type(desc))
print(type(profitable))

print("Tôi gửi ngân hàng $" + str(savings) + ", sau 15 năm, bây giờ tôi đã có $" + str(result) + ". Tuyệt vời!")
print(f"Toi gui ngan hang {savings}, sau 15 nam, bay gio toi da co {result} dong, tuyet voi!!")

hall = 20
kit = 18
liv = 20.0
bed = 10.75
bath = 9.50

areas = [hall, kit, liv, bed, bath]

print(areas)

x =["a", "b", "c", "d"]
print(x[-4])

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

eat_sleep_area = areas[3] + areas[-3]

print(eat_sleep_area)

areas = [2,3,"one","two",5,"four",7,"five"]
table = areas [:6]
beld = areas [3:]
print(table)
print(beld)

areas = [2,3,"one","two",5,"four",7,"five"]
areas[-3] = 4
areas[-2] ="seven"
print(areas)

areas =[1,"two",3,"four",5,"six",7,"eight",9,"ten"]
areas_1 = areas + [11,12]
areas_2 =list(areas_1)
areas_2.extend([13,14])
print(areas_1)
print(areas_2)

areas =[1,"two",3,"four",5,"six",7,"eight",9,"ten"]
del(areas[-3])
del(areas[2])
print(areas)

areas =[1,"two",3,"four",5,"six",7,"eight",9,"ten"]
areas_copy_1 = areas[:]
print(areas_copy_1)
areas_copy_2 = list(areas)
print(areas_copy_2)
areas_copy_1[0] = 11
print(areas_copy_1)

var1 = [1,"two",3,"four",5,"six",7,"eight",9,'ten']
var2 = True
print(type(var1))
print(len(var1))
out = int(var2)

help(complex)

help(sorted)

first = [1,4,7,9,12,15]
second = [3,6,20,23,34]
full = first + second
full_sorted_1 = sorted(full, reverse=True)
full_sorted_2 = sorted(full, reverse=False)
print(full_sorted_1)
print(full_sorted_2)









