# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDJxre_6WQjxetIbqaM_-BLlAeU5657g
"""

print(5/8)
print(7+10)
print("Hello Python")
print(4**2)
print(18%7)
print(1000*1.1**15)
savings = 20000
factor = 1.35
result = savings * factor ** 15
print (result)
desc = "uyuy"
profitable = True


print(type(savings))
print(type(factor))
print(type(desc))
print(type(profitable))

print("Tôi gửi ngân hàng $" + str(savings) + ", sau 15 năm, bây giờ tôi đã có $" + str(result) + ". Tuyệt vời!")
print(f"Toi gui ngan hang {savings}, sau 15 nam, bay gio toi da co {result} dong, tuyet voi!!")

hall = 20
kit = 18
liv = 20.0
bed = 10.75
bath = 9.50

areas = [hall, kit, liv, bed, bath]

print(areas)

x =["a", "b", "c", "d"]
print(x[-4])

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

eat_sleep_area = areas[3] + areas[-3]

print(eat_sleep_area)